#### Nessie + Notebook Playground Environment
services:
 spark-notebook:
   image: alexmerced/spark33-notebook
   ports:
     - "8888:8888"
 nessie:
   image: projectnessie/nessie
   ports:
     - "19120:19120"
 lensesio-box:
   image: lensesio/box
  #  command: docker run -e ADV_HOST=127.0.0.1 -e EULA="https://licenses.lenses.io/download/lensesdl?id=3f40a04b-193e-11ef-bf14-42010af01003" --rm
   environment:
      - EULA="https://licenses.lenses.io/download/lensesdl?id=3f40a04b-193e-11ef-bf14-42010af01003"
      - ADV_HOST=127.0.0.1
   ports:
     - "3030:3030"
     - "9092:9092"
 shadowtraffic:
   env_file:
       - license.env
   volumes:
       - ./hello-world.json:/home/config.json
   image: shadowtraffic/shadowtraffic:latest
   command: --config /home/config.json --watch --stdout